### ISSUE TITLE
Local business with reviews

### ISSUE THREAD

**Issue by Jaikant** [JayHoltslander/Structured-Data-JSON-LD#2]
Thanks for the nice work you have put up here.
Do you have an example for a Local business with reviews?

Can we do reviews for persons, like freelancers or would that be a local business. Would you know?

And finally, and hopefully my last question, can we show structured data with reviews for places?

Thanks Jay for the good work you have put up here, pretty helpful!

**Comment by JayHoltslander** [comment]
@Jaikant I'm not a master of Structured Data by any stretch but...
>The property aggregateRating is not recognized by Google for an object of type Person.

But... you can [make a Person a business as far as Google is concerned](https://goo.gl/maps/YwZToyTyjs52).

**Comment by JayHoltslander** [comment]
I will put up a LocalBusiness example in this repo soon. Still working on it.
