### ISSUE TITLE
unnamed item

### ISSUE THREAD

**Issue by noailjohn123** [JayHoltslander/Structured-Data-JSON-LD#4]
hello 
i added structured data for my website. www.lawwriting.co.uk when i am testing it show no error and no warning in structured data test tool and in rich result test tool. but it shows "unnamed item" with logos detection. i wanted to add "services" in structured data and what i see in rich results and google webmasters tool is there is "logos" i am helpless kindly help me fixed it what should i change in it. i have writing paper services. and different pages for different subject and types. so tell me this too that should i use same structured data for each page or different.

**Comment by JayHoltslander** [comment]
I see the services schema but I don't see "unnamed item" error in the SDTT. (Or a logo)

I tried adding a logo and the following SD worked:

````html
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Service",
  "serviceType": "law paper writing service",
  "url": "https://www.lawwriting.co.uk/",
  "provider": {
    "@type": "Organization",
    "name": "lawwriting"
  },
  "areaServed": {
  "@type": "State", 
  "name": "united kingdom",
  "logo": "https://placehold.it/32.jpg"
  } }
</script>
````

As for the Rich Results test, "Services" isn't supported.

From the docs:

> Supported rich result types
This test currently supports only the following rich result types:
>* Event
>* Fact check
>* Film (media type)
>* Job posting
>* Logo
>* Product
>* Q&A page
>* Recipe
>* Sitelinks searchbox
